image: haskell

stages:
  - build
  - test

before_script:
  - "export STACK_ROOT=$(pwd)/.stack"

build_stack:
  stage: build
  cache:
    paths:
      - .stack
  script:
    - "stack build --pedantic --copy-bins --local-bin-path .bins"
  artifacts:
    paths:
      - .bins

build_submission:
  stage: build
  cache:
    paths:
      - cwk/downloads
  script:
    - "apt install zip"
    - "cd cwk && ./build.sh"
    - "zip -r submission.zip submission/*"
  artifacts:
    paths:
      - cwk/submission.zip

test_stack:
  stage: test
  cache:
    paths:
      - .stack
    policy: pull
  script:
    - "stack test --coverage"
    - "cp -r $(stack path --local-hpc-root) .codecov"
  artifacts:
    paths:
      - .codecov

test_hlint:
  stage: test
  cache:
    policy: pull
  script:
    - "apt-get update && apt-get install hlint -y"
    - "hlint -r ."
  artifacts:
    paths:
      - report.html
    when: on_failure
  allow_failure: true

test_pawel:
  stage: test
  cache:
    policy: pull
  script:
    - "cp .bins/trout-exe cwk/cw-automarker/trout"
    - "cd cwk/cw-automarker && ./auto"
  allow_failure: true
