name:                trout
version:             0.1.0.0
author:              "Dan Trickey & Kajetan Champlewski"
maintainer:          "trout@trickey.io"
copyright:           "2019 Dan Trickey & Kajetan Champlewski"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/trout#readme>

dependencies:
- base >= 4.7 && < 5
- hspec
- megaparsec
- parser-combinators
- text
- mtl
- QuickCheck
- unordered-containers

library:
  source-dirs: src

executables:
  trout-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - trout

tests:
  trout-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - trout
